import { createContext, useContext, useState } from 'react';

const UI = {
  en: {
    // Nav
    nav_explore:   'Explore',
    nav_profile:   'Profile',
    nav_emergency: 'Emergency',
    nav_mchs:      'MChS Panel',
    nav_about:     'About',
    nav_dashboard: 'Dashboard',
    nav_logout:    'Log out',
    nav_in_trip:   'In progress',

    // Home
    home_eyebrow:     'Mangystau · Kazakhstan',
    home_title:       'Explore the\nWild Frontier',
    home_sub:         'Ancient canyons, salt flats, and cosmic landscapes at the edge of the Caspian Sea.',
    home_start:       'Start your journey →',
    home_view_all:    'View All Places',
    home_scroll:      'scroll',
    home_dest_label:  'Destinations',
    home_dest_for:    'For you,',
    home_dest_best:   'Best Destinations',
    home_active_trip: 'Active trip in progress',
    home_tap_track:   'Tap to view tracking',
    home_no_places:   'No places in this category yet',
    home_from:        'from Aktau',
    home_avg_rating:  'Avg rating',
    home_reviews:     'Reviews',
    cat_all:          'All',
    cat_sea:          'Sea',
    cat_beach:        'Beach',
    cat_mountain:     'Mountain',
    cat_canyon:       'Canyon',
    cat_popular:      'Popular',

    // Place Detail
    pd_back:       '← Back',
    pd_tab_info:   'Info',
    pd_tab_alerts: 'Alerts',
    pd_tab_weather:'Weather',
    pd_tab_map:    'Map',
    pd_quick:      'Quick Start',
    pd_plan:       'Plan Trip',
    pd_distance:   'km from Aktau',
    pd_checkpoints:'Checkpoints',
    pd_warnings:   'Warnings',
    pd_tips:       'Mama Tips',

    // Quick start / Plan trip
    qs_title:      'Ready to go?',
    qs_return:     '⏰ Return time',
    qs_vehicle:    '🚙 Vehicle',
    qs_plate:      '🔢 Plate number',
    qs_start:      'Start Trip — Register with MChS →',
    pt_title:      'Plan Your Trip',
    pt_clothing:   '🧥 Clothing description (for MChS)',
    pt_clothing_ph:'Describe your outfit for rescue teams…',
    pt_group:      '👥 Group type',
    pt_solo:       'Solo',
    pt_pair:       'Pair',
    pt_group3:     'Group',
    pt_contacts:   '📞 Emergency contacts',
    pt_contact_name:'Name',
    pt_contact_ph:  'Phone',
    contact_relation: 'Relation',
    rel_relative:  'Relative',
    rel_spouse:    'Spouse',
    rel_parent:    'Parent',
    rel_friend:    'Friend',
    rel_colleague: 'Colleague',
    rel_other:     'Other',
    pt_start:       'Start Trip →',
    pt_trip_type:  'Trip type',
    pt_type_solo:  '👤 Solo',
    pt_type_group: '👥 Group',
    pt_type_tour:  '🎯 Tour',
    pt_transport:  '🚙 Transport',
    pt_sos_auto_pre: 'If you don\'t check in by this deadline, an SOS is sent automatically',
    pt_sos_auto_post:'min later.',
    pt_pin_title:  'Your emergency PIN code',
    pt_pin_desc:   'Write this down — use it from any phone to send SOS if you lose your phone',
    pt_start_btn:  '🚀 Start Trip',
    place_not_found:'Place not found',

    // Tracking
    tr_title:      'In progress',
    tr_overdue:    'Return time passed!',
    tr_overdue_by: 'Overdue by',
    tr_overdue_was:'Return was at',
    tr_auto_sos_in:'Auto-SOS in',
    tr_returned:   'I\'m back ✅',
    tr_sos_sent:   'SOS sent — MChS notified',
    tr_sos_stay:   'Stay in place. Wait for confirmation from rescuers.',
    tr_sos_cancel_btn: 'Cancel SOS',
    tr_sos_cancel_title: 'Why are you cancelling?',
    tr_sos_cancel_reason_ok:       'I\'m fine, false alarm',
    tr_sos_cancel_reason_misclick: 'Pressed by accident',
    tr_sos_cancel_reason_resolved: 'Already helped, situation resolved',
    tr_sos_cancel_reason_other:    'Other reason',
    tr_sos_cancelled: 'SOS cancelled — trip continues',
    tr_min:        'min',
    tr_trip_info:  'Trip info (visible to MChS)',
    tr_clothing:   'Clothing:',
    tr_vehicle:    'Vehicle:',
    tr_sos_btn:    '🆘 SOS — EMERGENCY',
    tr_stop_btn:   '⏹ Stop Trip — I\'m safe',
    tr_sos_modal_title: 'Send SOS?',
    tr_sos_modal_sub:   'Your GPS location, profile and trip details will be sent immediately to MChS and your emergency contacts.',
    tr_cancel:     'Cancel',
    tr_send_sos:   'SEND SOS NOW',
    tr_end_trip:   'End trip?',
    tr_end_sub:    'Your contacts and MChS will be notified that you returned safely.',
    tr_continue:   'Continue trip',
    tr_end_safe:   "I'm safe, end trip",
    tr_no_trip:    'No active trip',
    tr_no_trip_sub:'Start a trip from the Home page',
    tr_browse:     'Browse places',
    tr_live_share:  'Share live location',
    tr_live_title:  'Live tracking',
    tr_live_sub:    'Scan with a phone to open a live map — no app or login needed.',
    tr_live_copy:   'Copy link',
    tr_live_copied: 'Copied!',
    tr_live_close:  'Close',
    tr_shake_enable: 'Enable shake-to-alert',
    tr_shake_active: '📳 Shake-to-alert is on — shake the phone 3× to ping MChS (not SOS)',
    tr_voice_sos_enable: 'Enable voice SOS',
    tr_voice_sos_active: '🎤 Voice SOS is on — say "help" / "көмек керек" to trigger SOS',
    tr_emergency_card: 'Emergency ID card',
    tr_emergency_card_title: 'Emergency info',
    tr_emergency_card_sub: 'Show this to a rescuer — works without internet or login.',
    tr_sms_fallback: 'Send SOS via SMS',
    tr_others_on_route: 'other tourists on this route right now',
    tr_route:      'Route Vibes',
    tr_checkpoints:'Checkpoints',

    // Profile
    prof_title:    'Profile',
    prof_sub:      'Your data is shared with MChS if you send SOS',
    prof_change:   'Tap 📷 to change photo',
    prof_verified: 'Verified ✓',
    prof_critical: 'CRITICAL FOR RESCUE',
    prof_gender:   'GENDER',
    prof_gender_male:   'Male',
    prof_gender_female: 'Female',
    prof_blood:    'BLOOD TYPE',
    prof_country:  'COUNTRY',
    prof_height:   'HEIGHT (CM)',
    prof_weight:   'WEIGHT (KG)',
    prof_allergies: 'ALLERGIES',
    prof_allergies_ph: 'e.g. penicillin, peanuts, bee stings',
    prof_marks:    'DISTINGUISHING MARKS',
    prof_marks_ph: 'Tattoos, piercings, scars, birthmarks — helps rescuers identify you',
    prof_fname:    'FIRST NAME',
    prof_lname:    'LAST NAME',
    prof_phone:    'PHONE',
    prof_email:    'EMAIL',
    prof_contacts: 'EMERGENCY CONTACTS',
    prof_add_contact: '+ Add contact',
    prof_save:     'Save Profile',
    prof_saved:    'Profile saved! ✅',
    prof_trips:    'trips completed',
    prof_next:     'Next:',

    // Pin / Emergency
    pin_title:     'Emergency SOS',
    pin_sub:       'Enter your PIN to send SOS without logging in',
    pin_enter:     'Enter PIN',
    pin_send:      'Send Emergency SOS',
    pin_wrong:     'Wrong PIN',
    pin_info:      '🔑 Enter the 6-digit PIN you got when planning your trip. Works from any phone.',
    pin_label:     '6-digit PIN code',
    pin_need6:     'PIN must be 6 digits',
    pin_attempts_left: '{n} attempts left.',
    pin_blocked_msg: '{max} wrong attempts. Wait {sec}s.',
    pin_blocked_wait: 'Blocked. Please wait.',
    pin_blocked_btn: '🔒 Blocked ({sec}s)',
    pin_submit:    'Find trip',
    pin_demo:      'Demo PIN:',
    pin_found:     '✅ Found:',
    pin_unknown:   'Unknown trip',
    pin_return:    'Return time:',
    pin_safe_btn:  '✅ Safe — End trip',
    pin_sos_btn:   '🆘 SEND SOS — Need help',

    // Admin login
    adm_title:     'MChS Admin Login',
    adm_sub:       'Access for MChS staff only',
    adm_login:     'LOGIN',
    adm_pass:      'PASSWORD',
    adm_btn:       'Log In',
    adm_wrong:     'Wrong credentials',

    // Auth (login / register)
    auth_login_title:    'Welcome back',
    auth_login_sub:      'Sign in to continue your journey',
    auth_register_title: 'Create account',
    auth_register_sub:   'Join DeadEnd and start exploring Mangystau',
    auth_email:          'Email',
    auth_password:       'Password',
    auth_firstname:      'First name',
    auth_lastname:       'Last name',
    auth_login_btn:      'Sign in',
    auth_register_btn:   'Create account',
    auth_no_account:     "Don't have an account?",
    auth_have_account:   'Already have an account?',
    auth_signup_link:    'Sign up',
    auth_signin_link:    'Sign in',
    auth_err_invalid:    'Invalid email or password',
    auth_err_exists:     'An account with this email already exists',
    auth_err_account_exists: 'An account with this email already exists. Sign in with your email and password instead.',
    auth_err_required:   'Please fill in all fields',
    auth_err_weak:       'Password must be at least 6 characters',
    auth_err_config:     'Sign-in is not configured yet. Please try again later.',
    auth_demo_hint:      'Demo account: james@gmail.com / demo1234',
    auth_or:             'or',
    auth_google_btn:     'Continue with Google',
    auth_forgot_link:    'Forgot password?',
    auth_forgot_title:   'Reset password',
    auth_forgot_sub:     "Enter your email and we'll send you a link to reset your password",
    auth_forgot_btn:     'Send reset link',
    auth_forgot_sent:    "If an account exists for that email, we've sent a password reset link.",
    auth_forgot_back:    'Back to sign in',

    // Place Detail extra
    pd_go:           'Go',
    pd_likes:        'likes',
    pd_show_more:    'more',
    pd_show_less:    'less',
    pd_contacts_none:'No contacts added',
    pd_notify:       '📞 Notify',
    pd_video:        'Video Tour',
    pd_drone:        'Drone footage · Mangystau',
    live_alerts:     '🔴 Live alerts',
    live_badge:      'LIVE',
    live_verified:   '✓ verified',
    wx_loading:      'Loading weather...',
    wx_wind:         'Wind',
    wx_humidity:     'Humidity',
    wx_rain:         'Rain',
    wx_today:        'Today',
    wx_tomorrow:     'Tomorrow',
    wx_mama_says:    '💜 Mama says',
    pd_hl_weather:   'Weather',
    pd_hl_risks:     'Risks',
    pd_hl_tips:      'Tips',
    pd_hl_gear:      'Gear',
    pd_hl_route:     'Route',
    pd_weather_now:  'Weather now',
    pd_route_warnings:'Route warnings',
    pd_mama_says:    'Mama says',
    pd_mama_sub:     '💜 Warm tips from local experience. Your safety matters.',
    pd_gear_title:   'What to bring',
    pd_pts:          'points',
    pd_from_start:   'km from start',
    pd_start_btn:    '🚀 Start Route',
    pd_ready:        'Ready to go?',
    home_featured:   'Featured Destination',
    home_explore:    'Explore route →',
    home_difficult:  'difficult',

    // General
    km:            'km',
    hrs:           'hrs',
    back:          '← Back',
    save:          'Save',
    cancel:        'Cancel',

    // AI Chat
    chat_title:       'Taumaru',
    chat_subtitle:    'Ask about routes & safety',
    chat_placeholder: 'Ask about a route...',
    chat_welcome:     "Hi, I'm Taumaru, the DeadEnd assistant! Ask me about routes in Mangystau, distances, difficulty, or what to pack — I can recommend a trip, or translate a phrase for talking to locals and rescuers.",
    chat_send:        'Send',
    chat_error:       'Something went wrong. Try again.',
    chat_listening:   'Listening…',
    chat_voice_on:    'Voice replies on',
    chat_voice_off:   'Voice replies off',
    chat_speak:       'Listen',
    chat_stop_speak:  'Stop',
  },

  ru: {
    nav_explore:   'Маршруты',
    nav_profile:   'Профиль',
    nav_emergency: 'Экстренный',
    nav_mchs:      'МЧС Панель',
    nav_about:     'О нас',
    nav_dashboard: 'Дашборд',
    nav_logout:    'Выйти',
    nav_in_trip:   'В пути',

    home_eyebrow:     'Мангыстау · Казахстан',
    home_title:       'Откройте\nДикие просторы',
    home_sub:         'Древние каньоны, солончаки и космические пейзажи на краю Каспийского моря.',
    home_start:       'Начать путешествие →',
    home_view_all:    'Все маршруты',
    home_scroll:      'листать',
    home_dest_label:  'Направления',
    home_dest_for:    'Для вас,',
    home_dest_best:   'Лучшие направления',
    home_active_trip: 'Поездка в процессе',
    home_tap_track:   'Нажмите для отслеживания',
    home_no_places:   'В этой категории пока нет мест',
    home_from:        'от Актау',
    home_avg_rating:  'Средний рейтинг',
    home_reviews:     'Отзывы',
    cat_all:          'Все',
    cat_sea:          'Море',
    cat_beach:        'Пляж',
    cat_mountain:     'Горы',
    cat_canyon:       'Каньон',
    cat_popular:      'Популярное',

    pd_back:       '← Назад',
    pd_tab_info:   'Инфо',
    pd_tab_alerts: 'Предупреждения',
    pd_tab_weather:'Погода',
    pd_tab_map:    'Карта',
    pd_quick:      'Быстрый старт',
    pd_plan:       'Планировать',
    pd_distance:   'км от Актау',
    pd_checkpoints:'Чекпоинты',
    pd_warnings:   'Опасности',
    pd_tips:       'Советы мамы',

    qs_title:      'Готов к старту?',
    qs_return:     '⏰ Время возврата',
    qs_vehicle:    '🚙 Транспорт',
    qs_plate:      '🔢 Номер авто',
    qs_start:      'Начать поездку — Зарегистрировать в МЧС →',
    pt_title:      'Планирование',
    pt_clothing:   '🧥 Описание одежды (для МЧС)',
    pt_clothing_ph:'Опишите одежду для спасателей…',
    pt_group:      '👥 Тип группы',
    pt_solo:       'Соло',
    pt_pair:       'Пара',
    pt_group3:     'Группа',
    pt_contacts:   '📞 Контакты для экстренной связи',
    pt_contact_name:'Имя',
    pt_contact_ph:  'Телефон',
    contact_relation: 'Кто это',
    rel_relative:  'Родственник',
    rel_spouse:    'Супруг(а)',
    rel_parent:    'Родитель',
    rel_friend:    'Друг',
    rel_colleague: 'Коллега',
    rel_other:     'Другое',
    pt_start:       'Начать →',
    pt_trip_type:  'Тип поездки',
    pt_type_solo:  '👤 Соло',
    pt_type_group: '👥 Группа',
    pt_type_tour:  '🎯 Тур',
    pt_transport:  '🚙 Транспорт',
    pt_sos_auto_pre: 'Если вы не отметитесь до этого времени, SOS будет отправлен автоматически через',
    pt_sos_auto_post:'мин.',
    pt_pin_title:  'Ваш экстренный PIN-код',
    pt_pin_desc:   'Запишите его — используйте с любого телефона, чтобы отправить SOS, если потеряете свой',
    pt_start_btn:  '🚀 Начать поездку',
    place_not_found:'Место не найдено',

    tr_title:      'В пути',
    tr_overdue:    'Время возврата прошло!',
    tr_overdue_by: 'Просрочено на',
    tr_overdue_was:'Возврат был в',
    tr_auto_sos_in:'Авто-SOS через',
    tr_returned:   'Я вернулся ✅',
    tr_sos_sent:   'SOS отправлен — МЧС оповещены',
    tr_sos_stay:   'Оставайтесь на месте. Ждите подтверждения от спасателей.',
    tr_sos_cancel_btn: 'Отменить SOS',
    tr_sos_cancel_title: 'Укажите причину отмены',
    tr_sos_cancel_reason_ok:       'Всё в порядке, ложный вызов',
    tr_sos_cancel_reason_misclick: 'Случайно нажал(а)',
    tr_sos_cancel_reason_resolved: 'Уже помогли, ситуация решена',
    tr_sos_cancel_reason_other:    'Другая причина',
    tr_sos_cancelled: 'SOS отменён — поездка продолжается',
    tr_min:        'мин',
    tr_trip_info:  'Данные поездки (видны МЧС)',
    tr_clothing:   'Одежда:',
    tr_vehicle:    'Транспорт:',
    tr_sos_btn:    '🆘 SOS — ЭКСТРЕННЫЙ ВЫЗОВ',
    tr_stop_btn:   '⏹ Завершить — Я в безопасности',
    tr_sos_modal_title: 'Отправить SOS?',
    tr_sos_modal_sub:   'Ваши GPS-координаты, профиль и данные поездки будут немедленно отправлены в МЧС и экстренным контактам.',
    tr_cancel:     'Отмена',
    tr_send_sos:   'ОТПРАВИТЬ SOS',
    tr_end_trip:   'Завершить поездку?',
    tr_end_sub:    'Ваши контакты и МЧС получат уведомление о безопасном возвращении.',
    tr_continue:   'Продолжить',
    tr_end_safe:   'Я в безопасности',
    tr_no_trip:    'Нет активной поездки',
    tr_no_trip_sub:'Начните поездку с главной страницы',
    tr_browse:     'Смотреть маршруты',
    tr_live_share:  'Поделиться геолокацией',
    tr_live_title:  'Живой трек',
    tr_live_sub:    'Отсканируйте телефоном — откроется карта в реальном времени, без приложения и входа.',
    tr_live_copy:   'Копировать ссылку',
    tr_live_copied: 'Скопировано!',
    tr_live_close:  'Закрыть',
    tr_shake_enable: 'Включить шейк-сигнал',
    tr_shake_active: '📳 Шейк-сигнал включён — встряхните телефон 3× чтобы предупредить МЧС (это не SOS)',
    tr_voice_sos_enable: 'Включить голосовой SOS',
    tr_voice_sos_active: '🎤 Голосовой SOS включён — скажите "помогите" / "көмек керек" для вызова SOS',
    tr_emergency_card: 'Медкарта для спасателей',
    tr_emergency_card_title: 'Экстренная информация',
    tr_emergency_card_sub: 'Покажите это спасателю — работает без интернета и входа.',
    tr_sms_fallback: 'Отправить SOS по SMS',
    tr_others_on_route: 'других туристов сейчас на этом маршруте',
    tr_route:      'Маршрутные ритмы',
    tr_checkpoints:'Чекпоинты',

    prof_title:    'Профиль',
    prof_sub:      'Данные передаются МЧС при отправке SOS',
    prof_change:   'Нажмите 📷 чтобы сменить фото',
    prof_verified: 'Подтверждён ✓',
    prof_critical: 'ВАЖНО ДЛЯ СПАСЕНИЯ',
    prof_gender:   'ПОЛ',
    prof_gender_male:   'Мужской',
    prof_gender_female: 'Женский',
    prof_blood:    'ГРУППА КРОВИ',
    prof_country:  'СТРАНА',
    prof_height:   'РОСТ (СМ)',
    prof_weight:   'ВЕС (КГ)',
    prof_allergies: 'АЛЛЕРГИИ',
    prof_allergies_ph: 'напр. пенициллин, орехи, укусы пчёл',
    prof_marks:    'ОСОБЫЕ ПРИМЕТЫ',
    prof_marks_ph: 'Татуировки, пирсинг, шрамы, родинки — поможет спасателям опознать вас',
    prof_fname:    'ИМЯ',
    prof_lname:    'ФАМИЛИЯ',
    prof_phone:    'ТЕЛЕФОН',
    prof_email:    'EMAIL',
    prof_contacts: 'КОНТАКТЫ ДЛЯ ЭКСТРЕННОЙ СВЯЗИ',
    prof_add_contact: '+ Добавить контакт',
    prof_save:     'Сохранить профиль',
    prof_saved:    'Профиль сохранён! ✅',
    prof_trips:    'поездок завершено',
    prof_next:     'Следующий:',

    pin_title:     'Экстренный SOS',
    pin_sub:       'Введите PIN для отправки SOS без входа в аккаунт',
    pin_enter:     'Введите PIN',
    pin_send:      'Отправить экстренный SOS',
    pin_wrong:     'Неверный PIN',
    pin_info:      '🔑 Введите 6-значный PIN, который вы получили при планировании поездки. Работает с любого телефона.',
    pin_label:     '6-значный PIN-код',
    pin_need6:     'PIN должен содержать 6 цифр',
    pin_attempts_left: 'Осталось попыток: {n}.',
    pin_blocked_msg: '{max} неверных попыток. Подождите {sec} с.',
    pin_blocked_wait: 'Блокировка. Подождите.',
    pin_blocked_btn: '🔒 Блокировка ({sec}с)',
    pin_submit:    'Найти поездку',
    pin_demo:      'Демо PIN:',
    pin_found:     '✅ Найдено:',
    pin_unknown:   'Маршрут неизвестен',
    pin_return:    'Время возвращения:',
    pin_safe_btn:  '✅ В безопасности — Завершить поездку',
    pin_sos_btn:   '🆘 ОТПРАВИТЬ SOS — Нужна помощь',

    adm_title:     'МЧС Вход',
    adm_sub:       'Доступ только для сотрудников МЧС',
    adm_login:     'ЛОГИН',
    adm_pass:      'ПАРОЛЬ',
    adm_btn:       'Войти',
    adm_wrong:     'Неверные данные',

    // Auth (вход / регистрация)
    auth_login_title:    'С возвращением',
    auth_login_sub:      'Войдите, чтобы продолжить путешествие',
    auth_register_title: 'Создать аккаунт',
    auth_register_sub:   'Присоединяйтесь к DeadEnd и начните исследовать Мангистау',
    auth_email:          'Email',
    auth_password:       'Пароль',
    auth_firstname:      'Имя',
    auth_lastname:       'Фамилия',
    auth_login_btn:      'Войти',
    auth_register_btn:   'Создать аккаунт',
    auth_no_account:     'Нет аккаунта?',
    auth_have_account:   'Уже есть аккаунт?',
    auth_signup_link:    'Зарегистрироваться',
    auth_signin_link:    'Войти',
    auth_err_invalid:    'Неверный email или пароль',
    auth_err_exists:     'Аккаунт с таким email уже существует',
    auth_err_account_exists: 'Аккаунт с таким email уже зарегистрирован с паролем. Войдите по email и паролю.',
    auth_err_required:   'Заполните все поля',
    auth_err_weak:       'Пароль должен быть не короче 6 символов',
    auth_err_config:     'Вход временно не настроен. Попробуйте позже.',
    auth_demo_hint:      'Демо-аккаунт: james@gmail.com / demo1234',
    auth_or:             'или',
    auth_google_btn:     'Войти через Google',
    auth_forgot_link:    'Забыли пароль?',
    auth_forgot_title:   'Восстановление пароля',
    auth_forgot_sub:     'Введите email — мы отправим ссылку для сброса пароля',
    auth_forgot_btn:     'Отправить ссылку',
    auth_forgot_sent:    'Если аккаунт с таким email существует, мы отправили на него ссылку для сброса пароля.',
    auth_forgot_back:    'Назад ко входу',

    // Place Detail extra
    pd_go:           'Поехать',
    pd_likes:        'отметок',
    pd_show_more:    'ещё',
    pd_show_less:    'скрыть',
    pd_contacts_none:'Контакты не добавлены',
    pd_notify:       '📞 Уведомим',
    pd_video:        'Видео-обзор',
    pd_drone:        'Снято с дрона · Мангыстау',
    pd_hl_weather:   'Погода',
    pd_hl_risks:     'Риски',
    pd_hl_tips:      'Советы',
    pd_hl_gear:      'Снаряжение',
    pd_hl_route:     'Маршрут',
    pd_weather_now:  'Погода сейчас',
    pd_route_warnings:'Предупреждения маршрута',
    pd_mama_says:    'Мама говорит',
    pd_mama_sub:     '💜 Тёплые советы из местного опыта. Ваша безопасность важна для нас.',
    pd_gear_title:   'Что взять с собой',
    pd_pts:          'точек',
    pd_from_start:   'км от старта',
    pd_start_btn:    '🚀 Начать маршрут',
    pd_ready:        'Готов к старту?',
    home_featured:   'Рекомендуем',
    home_explore:    'Исследовать →',
    home_difficult:  'сложные',

    // Live alerts
    live_alerts:     '🔴 Новости в реальном времени',
    live_badge:      'LIVE',
    live_verified:   '✓ подтверждено',

    // Weather widget
    wx_loading:      'Погода загружается...',
    wx_wind:         'Ветер',
    wx_humidity:     'Влажность',
    wx_rain:         'Дождь',
    wx_today:        'Сегодня',
    wx_tomorrow:     'Завтра',
    wx_mama_says:    '💜 Советы мамы',

    km:            'км',
    hrs:           'ч',
    back:          '← Назад',
    save:          'Сохранить',
    cancel:        'Отмена',

    // AI Chat
    chat_title:       'Таумару',
    chat_subtitle:    'Вопросы о маршрутах и безопасности',
    chat_placeholder: 'Спросите про маршрут...',
    chat_welcome:     'Привет, я Таумару, ассистент DeadEnd! Спросите про маршруты по Мангистау, расстояния, сложность, что взять с собой — подберу поездку, а ещё могу перевести фразу для разговора с местными или спасателями.',
    chat_send:        'Отправить',
    chat_error:       'Что-то пошло не так. Попробуйте ещё раз.',
    chat_listening:   'Слушаю…',
    chat_voice_on:    'Озвучка включена',
    chat_voice_off:   'Озвучка выключена',
    chat_speak:       'Озвучить',
    chat_stop_speak:  'Остановить',
  },

  kz: {
    nav_explore:   'Маршруттар',
    nav_profile:   'Профиль',
    nav_emergency: 'Шұғыл',
    nav_mchs:      'ТЖМ Панель',
    nav_about:     'Біз туралы',
    nav_dashboard: 'Дашборд',
    nav_logout:    'Шығу',
    nav_in_trip:   'Жолда',

    home_eyebrow:     'Маңғыстау · Қазақстан',
    home_title:       'Жабайы табиғатты\nашыңыз',
    home_sub:         'Каспий теңізінің жағасындағы ежелгі шатқалдар, тұзды жазықтар және ғарыштық пейзаждар.',
    home_start:       'Сапарды бастау →',
    home_view_all:    'Барлық орындар',
    home_scroll:      'жылжыту',
    home_dest_label:  'Бағыттар',
    home_dest_for:    'Сізге,',
    home_dest_best:   'Ең жақсы бағыттар',
    home_active_trip: 'Сапар жүріп жатыр',
    home_tap_track:   'Бақылауды көру үшін басыңыз',
    home_no_places:   'Бұл санатта орын жоқ',
    home_from:        'Ақтаудан',
    home_avg_rating:  'Орташа рейтинг',
    home_reviews:     'Пікірлер',
    cat_all:          'Барлығы',
    cat_sea:          'Теңіз',
    cat_beach:        'Жағажай',
    cat_mountain:     'Тау',
    cat_canyon:       'Шатқал',
    cat_popular:      'Танымал',

    pd_back:       '← Артқа',
    pd_tab_info:   'Ақпарат',
    pd_tab_alerts: 'Ескертулер',
    pd_tab_weather:'Ауа райы',
    pd_tab_map:    'Карта',
    pd_quick:      'Жылдам бастау',
    pd_plan:       'Жоспарлау',
    pd_distance:   'км Ақтаудан',
    pd_checkpoints:'Бекеттер',
    pd_warnings:   'Қауіптер',
    pd_tips:       'Ана кеңестері',

    qs_title:      'Жолға шығуға дайынсыз ба?',
    qs_return:     '⏰ Қайту уақыты',
    qs_vehicle:    '🚙 Көлік',
    qs_plate:      '🔢 Нөмірі',
    qs_start:      'Сапарды бастау — ТЖМ-ге тіркеу →',
    pt_title:      'Сапарды жоспарлау',
    pt_clothing:   '🧥 Киім сипаттамасы (ТЖМ үшін)',
    pt_clothing_ph:'Құтқарушылар үшін киімді сипаттаңыз…',
    pt_group:      '👥 Топ түрі',
    pt_solo:       'Жеке',
    pt_pair:       'Жұп',
    pt_group3:     'Топ',
    pt_contacts:   '📞 Шұғыл байланыс',
    pt_contact_name:'Аты',
    pt_contact_ph:  'Телефон',
    contact_relation: 'Кім болады',
    rel_relative:  'Туыс',
    rel_spouse:    'Жұбайы',
    rel_parent:    'Ата-ана',
    rel_friend:    'Дос',
    rel_colleague: 'Әріптес',
    rel_other:     'Басқа',
    pt_start:       'Бастау →',
    pt_trip_type:  'Сапар түрі',
    pt_type_solo:  '👤 Жеке',
    pt_type_group: '👥 Топ',
    pt_type_tour:  '🎯 Тур',
    pt_transport:  '🚙 Көлік',
    pt_sos_auto_pre: 'Осы уақытқа дейін белгі бермесеңіз,',
    pt_sos_auto_post:'минуттан кейін SOS автоматты түрде жіберіледі.',
    pt_pin_title:  'Сіздің шұғыл PIN-кодыңыз',
    pt_pin_desc:   'Жазып алыңыз — телефоныңызды жоғалтсаңыз, кез келген телефоннан SOS жіберу үшін осыны пайдаланыңыз',
    pt_start_btn:  '🚀 Сапарды бастау',
    place_not_found:'Орын табылмады',

    tr_title:      'Жолда',
    tr_overdue:    'Қайту уақыты өтті!',
    tr_overdue_by: 'Кешіктірілді',
    tr_overdue_was:'Қайту уақыты болды',
    tr_auto_sos_in:'Авто-SOS дейін',
    tr_returned:   'Қайттым ✅',
    tr_sos_sent:   'SOS жіберілді — ТЖМ хабардар етілді',
    tr_sos_stay:   'Орныңызда қалыңыз. Құтқарушылардан растауды күтіңіз.',
    tr_sos_cancel_btn: 'SOS-ты болдырмау',
    tr_sos_cancel_title: 'Болдырмау себебін көрсетіңіз',
    tr_sos_cancel_reason_ok:       'Бәрі жақсы, қате дабыл',
    tr_sos_cancel_reason_misclick: 'Кездейсоқ бастым',
    tr_sos_cancel_reason_resolved: 'Көмек көрсетілді, мәселе шешілді',
    tr_sos_cancel_reason_other:    'Басқа себеп',
    tr_sos_cancelled: 'SOS болдырылмады — сапар жалғасады',
    tr_min:        'мин',
    tr_trip_info:  'Сапар деректері (ТЖМ-ге көрінеді)',
    tr_clothing:   'Киім:',
    tr_vehicle:    'Көлік:',
    tr_sos_btn:    '🆘 SOS — ШҰҒЫЛ ҚОҢЫРАУ',
    tr_stop_btn:   '⏹ Аяқтау — Мен қауіпсіздікте',
    tr_sos_modal_title: 'SOS жіберу?',
    tr_sos_modal_sub:   'GPS-координаттарыңыз, профиліңіз және сапар деректері ТЖМ-ге және шұғыл контакттарға лезде жіберіледі.',
    tr_cancel:     'Болдырмау',
    tr_send_sos:   'SOS ЖІБЕРУ',
    tr_end_trip:   'Сапарды аяқтау?',
    tr_end_sub:    'Контакттарыңыз бен ТЖМ қауіпсіз оралғаныңыз туралы хабардар болады.',
    tr_continue:   'Жалғастыру',
    tr_end_safe:   'Мен қауіпсіздікте',
    tr_no_trip:    'Белсенді сапар жоқ',
    tr_no_trip_sub:'Бас беттен сапар бастаңыз',
    tr_browse:     'Маршруттарды қарау',
    tr_live_share:  'Тірі геолокацияны бөлісу',
    tr_live_title:  'Тірі трек',
    tr_live_sub:    'Телефонмен сканерлеңіз — қолданбасыз және тіркеусіз карта ашылады.',
    tr_live_copy:   'Сілтемені көшіру',
    tr_live_copied: 'Көшірілді!',
    tr_live_close:  'Жабу',
    tr_shake_enable: 'Шейк-сигналды қосу',
    tr_shake_active: '📳 Шейк-сигнал қосулы — телефонды 3 рет шайқаңыз, ТЖМ-ге хабарланады (бұл SOS емес)',
    tr_voice_sos_enable: 'Дауыспен SOS қосу',
    tr_voice_sos_active: '🎤 Дауыспен SOS қосулы — "көмек керек" деп айтсаңыз, SOS автоматты жіберіледі',
    tr_emergency_card: 'Құтқарушыға медкарта',
    tr_emergency_card_title: 'Жедел медициналық ақпарат',
    tr_emergency_card_sub: 'Мұны құтқарушыға көрсетіңіз — интернетсіз және тіркеусіз жұмыс істейді.',
    tr_sms_fallback: 'SOS-ты SMS арқылы жіберу',
    tr_others_on_route: 'турист қазір осы бағытта жүріп жатыр',
    tr_route:      'Жол ырғақтары',
    tr_checkpoints:'Бекеттер',

    prof_title:    'Профиль',
    prof_sub:      'Деректер SOS кезінде ТЖМ-ге жіберіледі',
    prof_change:   'Фотоны өзгерту үшін 📷 басыңыз',
    prof_verified: 'Расталды ✓',
    prof_critical: 'ҚҰТҚАРУ ҮШІН МАҢЫЗДЫ',
    prof_gender:   'ЖЫНЫСЫ',
    prof_gender_male:   'Ер',
    prof_gender_female: 'Әйел',
    prof_blood:    'ҚАН ТОБЫ',
    prof_country:  'ЕЛ',
    prof_height:   'БОЙ (СМ)',
    prof_weight:   'САЛМАҚ (КГ)',
    prof_allergies: 'АЛЛЕРГИЯ',
    prof_allergies_ph: 'мыс. пенициллин, жержаңғақ, ара шағуы',
    prof_marks:    'ЕРЕКШЕ БЕЛГІЛЕР',
    prof_marks_ph: 'Татуировка, пирсинг, тыртық, меңдер — құтқарушыларға танып алуға көмектеседі',
    prof_fname:    'АТЫ',
    prof_lname:    'ТЕГІ',
    prof_phone:    'ТЕЛЕФОН',
    prof_email:    'EMAIL',
    prof_contacts: 'ШҰҒЫЛ БАЙЛАНЫС',
    prof_add_contact: '+ Байланыс қосу',
    prof_save:     'Профильді сақтау',
    prof_saved:    'Профиль сақталды! ✅',
    prof_trips:    'сапар аяқталды',
    prof_next:     'Келесі:',

    pin_title:     'Шұғыл SOS',
    pin_sub:       'Кіруден кіреберіссіз SOS жіберу үшін PIN енгізіңіз',
    pin_enter:     'PIN енгізіңіз',
    pin_send:      'Шұғыл SOS жіберу',
    pin_wrong:     'Қате PIN',
    pin_info:      '🔑 Сапарды жоспарлағанда алған 6 цифрлы PIN-кодты енгізіңіз. Кез келген телефоннан жұмыс істейді.',
    pin_label:     '6 цифрлы PIN код',
    pin_need6:     'PIN 6 цифр болуы керек',
    pin_attempts_left: '{n} рет мүмкіндік қалды.',
    pin_blocked_msg: '{max} рет қате. {sec} секунд күтіңіз.',
    pin_blocked_wait: 'Блокталған. Күте тұрыңыз.',
    pin_blocked_btn: '🔒 Блокталған ({sec}с)',
    pin_submit:    'Сапарды табу',
    pin_demo:      'Демо PIN:',
    pin_found:     '✅ Табылды:',
    pin_unknown:   'Белгісіз сапар',
    pin_return:    'Қайту уақыты:',
    pin_safe_btn:  '✅ Қауіпсіздікте — Сапарды аяқтау',
    pin_sos_btn:   '🆘 SOS ЖІБЕРУ — Көмек керек',

    adm_title:     'ТЖМ Кіру',
    adm_sub:       'Тек ТЖМ қызметкерлеріне кіру',
    adm_login:     'ЛОГИН',
    adm_pass:      'ПАРОЛЬ',
    adm_btn:       'Кіру',
    adm_wrong:     'Қате деректер',

    // Auth (кіру / тіркелу)
    auth_login_title:    'Қош келдіңіз',
    auth_login_sub:      'Сапарды жалғастыру үшін кіріңіз',
    auth_register_title: 'Аккаунт құру',
    auth_register_sub:   'DeadEnd-ке қосылып, Маңғыстауды зерттеуді бастаңыз',
    auth_email:          'Email',
    auth_password:       'Құпия сөз',
    auth_firstname:      'Аты',
    auth_lastname:       'Тегі',
    auth_login_btn:      'Кіру',
    auth_register_btn:   'Аккаунт құру',
    auth_no_account:     'Аккаунтыңыз жоқ па?',
    auth_have_account:   'Аккаунтыңыз бар ма?',
    auth_signup_link:    'Тіркелу',
    auth_signin_link:    'Кіру',
    auth_err_invalid:    'Email немесе құпия сөз қате',
    auth_err_exists:     'Бұл email-мен аккаунт бұрыннан бар',
    auth_err_account_exists: 'Бұл email-мен аккаунт парольмен тіркелген. Email және парольмен кіріңіз.',
    auth_err_required:   'Барлық өрістерді толтырыңыз',
    auth_err_weak:       'Құпия сөз кемінде 6 таңбадан тұруы керек',
    auth_err_config:     'Кіру әлі баптаулмаған. Кейінірек қайталап көріңіз.',
    auth_demo_hint:      'Демо аккаунт: james@gmail.com / demo1234',
    auth_or:             'немесе',
    auth_google_btn:     'Google арқылы кіру',
    auth_forgot_link:    'Құпия сөзді ұмыттыңыз ба?',
    auth_forgot_title:   'Құпия сөзді қалпына келтіру',
    auth_forgot_sub:     'Email енгізіңіз — біз сізге құпия сөзді қалпына келтіру сілтемесін жібереміз',
    auth_forgot_btn:     'Сілтеме жіберу',
    auth_forgot_sent:    'Егер бұл email-мен аккаунт бар болса, оған құпия сөзді қалпына келтіру сілтемесі жіберілді.',
    auth_forgot_back:    'Кіруге оралу',

    // Place Detail extra
    pd_go:           'Жолға',
    pd_likes:        'белгілер',
    pd_show_more:    'толығырақ',
    pd_show_less:    'жасыру',
    pd_contacts_none:'Контакттар қосылмаған',
    pd_notify:       '📞 Хабарлаймыз',
    pd_video:        'Бейнешолу',
    pd_drone:        'Дрон түсірілімі · Маңғыстау',
    live_alerts:     '🔴 Жедел жаңалықтар',
    live_badge:      'LIVE',
    live_verified:   '✓ расталған',
    wx_loading:      'Ауа-райы жүктелуде...',
    wx_wind:         'Жел',
    wx_humidity:     'Ылғал',
    wx_rain:         'Жаңбыр',
    wx_today:        'Бүгін',
    wx_tomorrow:     'Ертең',
    wx_mama_says:    '💜 Ана кеңесі',
    pd_hl_weather:   'Ауа райы',
    pd_hl_risks:     'Тәуекелдер',
    pd_hl_tips:      'Кеңестер',
    pd_hl_gear:      'Жабдық',
    pd_hl_route:     'Маршрут',
    pd_weather_now:  'Ауа райы қазір',
    pd_route_warnings:'Маршрут ескертулері',
    pd_mama_says:    'Ана айтады',
    pd_mama_sub:     '💜 Жылы кеңестер, жергілікті тәжірибеден. Сіздің қауіпсіздігіңіз — бізге маңызды.',
    pd_gear_title:   'Не алу керек',
    pd_pts:          'нүкте',
    pd_from_start:   'км бастаудан',
    pd_start_btn:    '🚀 Маршрутты бастау',
    pd_ready:        'Жолға шығуға дайынсыз ба?',
    home_featured:   'Таңдаулы бағыт',
    home_explore:    'Зерттеу →',
    home_difficult:  'күрделі',

    km:            'км',
    hrs:           'сағ',
    back:          '← Артқа',
    save:          'Сақтау',
    cancel:        'Болдырмау',

    // AI Chat
    chat_title:       'Таумару',
    chat_subtitle:    'Маршрут пен қауіпсіздік туралы сұрақтар',
    chat_placeholder: 'Маршрут туралы сұраңыз...',
    chat_welcome:     'Сәлем, мен Таумарумын, DeadEnd көмекшісі! Маңғыстау маршруттары, қашықтық, қиындық немесе не алу керектігі туралы сұраңыз — сапар таңдап беремін, сонымен қатар жергілікті тұрғындармен немесе құтқарушылармен сөйлесу үшін фразаны аударып бере аламын.',
    chat_send:        'Жіберу',
    chat_error:       'Бірдеңе дұрыс болмады. Қайталап көріңіз.',
    chat_listening:   'Тыңдап жатырмын…',
    chat_voice_on:    'Дауыс қосулы',
    chat_voice_off:   'Дауыс өшірулі',
    chat_speak:       'Дыбыстау',
    chat_stop_speak:  'Тоқтату',
  },
};

const LangContext = createContext(null);

export function LangProvider({ children }) {
  const stored = typeof window !== 'undefined' ? (localStorage.getItem('deadend_lang') || 'ru') : 'ru';
  const [lang, setLangState] = useState(stored);

  function setLang(l) {
    setLangState(l);
    localStorage.setItem('deadend_lang', l);
  }

  return (
    <LangContext.Provider value={{ lang, setLang, t: UI[lang] }}>
      {children}
    </LangContext.Provider>
  );
}

export function useLang() {
  return useContext(LangContext);
}
